name: Merge changes

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]
    types: [opened, synchronize]

jobs:
  
  redundancy:
    runs-on: ubuntu-20.04
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

  linter: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node_version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    needs: [linter]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node_version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test  
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
